language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tjabane/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tjabane/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-083236386774"
  bucket_path: "Docker React"
    on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY